import type { Metadata } from 'next';
import './globals.css';
import { Arvo, Nunito } from 'next/font/google';
import { Sidebar } from '@/components';

const arvo = Arvo({
  variable: '--font-arvo',
  subsets: ['latin'],
  weight: '400',
});

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`flex bg-off-white ${arvo.variable} ${nunito.variable} antialiased text-night`}
      >
        <Sidebar />
        <div className='p-8'>{children}</div>
      </body>
    </html>
  );
}
